#--------------------product and categories 
from webservices.views.product.BasicInformation import SaveAllImportedBarcodes,PreviewImportedBarcodes,ImportBarcodes,MultipleBarcodes,BasicInformationViewSet,BasicInformationLoadViewSet,ProductList,BasicProductSet,ProductImageDelete,SetCoverImage,GetProductChild,ProductList,GetBarcodeDetails
from webservices.views.product.AdvanceInformation import AdvanceInformationViewSet,AdvanceInformationLoadViewSet
from webservices.views.product.Productsetup import SaveAllImportedRelated,PreviewSaveFileRelated,SaveFileRelatedData,ImportFileRelatedProducts,Productsetup,ViewProductDetails,ViewProductInventoryDetails,ViewProductPurchaseOrderDetails,ViewProductReceiptDetails,ViewProductOrderDetails,ViewProductInvoiceDetails,ViewProductAdjustmentDetails,ImportFileProducts,SaveFileData,PreviewSaveFileData,SaveAllImportedData,GetChildCategory,ProductExport, getEanProduct, uploadImage, ProductSyncManual, ProductDesyncManual
from webservices.views.product.Reviews import ReviewsList,flag,ProductReviews
from webservices.views.product.Discount import CouponExport,DiscountProductFree,DiscountCouponCondition,SaveAllImportedDiscounts,PreviewSaveFileDiscounts,SaveFileDiscounts,ImportFileDiscounts,CatrgoryConditionsSet,DiscountSet,DiscountList,DiscountConditions,DiscountConditionsSet,CustomerGroupDiscount,CategoryLoed,Getchild_category,ProductLoad,CustomerLoed,CustomerType,DiscountCustomer,CategoriesListDiscount, ProductLoadPaging
from webservices.views.product.Brand import BrandList,Brand
from webservices.views.product.ContactGroup import ContactViewSet,ContactList
from webservices.views.product.Contacts import ContactsSetView,ContactsList,Contacts
from webservices.views.product.Segments import Segments,SegmentsList
from webservices.views.product.ProductDefaultPrice import DefaultPriceList
from webservices.views.product.Relatedproduct import VariableProductList,RelatedProductList,RelatedProductSet
from webservices.views.product.Categories import CategoryBannerImageDelete,CategoryBanner,CategoryExport,ChannelMapping,child,CategoriesInfoViewSet,CategoriesList,BasicInfoLoad,Image,Getchild,ImageDelete, AllImageUpload, CategoryBannerNew
from webservices.views.product.PricingandVariant import Productpricingadd,ProductpriceSet,ProductpriceSetView,AllProductImages
from webservices.views.product.Customfield import customfields,customfieldsedit,field_list,positionchange,customfieldsimport,customvalueupdate,customfieldsystem,customsuccessfieldimport,Channelscustomfield
from webservices.views.product.Hsncode import HsncodeSetup,HsncodeExport,HsnCodeList
from webservices.views.product.PromotionSetup import ProductPromotionImport
from webservices.views.product.Taxation import saveprice_temp_to_table,save_price_from_temp_to_table,SaveAllImportedPrice,PreviewSaveFilePrice,SaveFilePriceData,ImportFilePriceProducts,ChannelCurrencyPriceDelete,ChannelCurrencyProductPrice,ProductWareHouse,ProductPriceTypeList,PriceType,ProductPriceType,TaxSettings,ProductTaxClass,CustomerTaxClass,TaxRate,TaxRule
from webservices.views.product.GiftCard import *
from webservices.views.product.ProductDetails import *