# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-13 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0003_engageboostcategorymasters_engageboostproductcategories_engageboostproductimages_engageboostproducti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engageboostorderproducts',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='engageboostorderproducts',
            name='product_id',
        ),
        migrations.AddField(
            model_name='engageboostorderproducts',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='webservices.EngageboostOrdermaster'),
        ),
        migrations.AddField(
            model_name='engageboostorderproducts',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webservices.EngageboostProducts'),
        ),
    ]
