# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-13 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0005_auto_20190213_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngageboostAppCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appcategory', models.CharField(blank=True, max_length=222, null=True)),
                ('numberofapp', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'engageboost_app_category',
            },
        ),
        migrations.CreateModel(
            name='EngageboostAppMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appimage', models.CharField(blank=True, max_length=222, null=True)),
                ('apptitle', models.CharField(blank=True, max_length=222, null=True)),
                ('appnumrating', models.IntegerField(blank=True, null=True)),
                ('apptotalrating', models.IntegerField(blank=True, null=True)),
                ('appdescription', models.TextField(blank=True, null=True)),
                ('appnotes', models.TextField(blank=True, null=True)),
                ('appvideo', models.TextField(blank=True, null=True)),
                ('apprice', models.FloatField(blank=True, null=True)),
                ('appnuminstall', models.IntegerField(blank=True, null=True)),
                ('appcategory', models.IntegerField(blank=True, null=True)),
                ('otherimages', models.TextField(blank=True, null=True)),
                ('techsupportmailid', models.CharField(blank=True, max_length=222, null=True)),
                ('appdeveloper', models.CharField(blank=True, max_length=222, null=True)),
                ('freetrial', models.IntegerField(blank=True, null=True)),
                ('apppath', models.CharField(blank=True, max_length=222, null=True)),
            ],
            options={
                'db_table': 'engageboost_app_master',
            },
        ),
        migrations.CreateModel(
            name='EngageboostAppReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.IntegerField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('reviewby', models.CharField(blank=True, max_length=222, null=True)),
                ('reviewdate', models.DateField(blank=True, null=True)),
                ('customerid', models.IntegerField(blank=True, null=True)),
                ('reviewrate', models.IntegerField(blank=True, null=True)),
                ('reviewtitle', models.CharField(blank=True, max_length=222, null=True)),
            ],
            options={
                'db_table': 'engageboost_app_reviews',
            },
        ),
        migrations.CreateModel(
            name='EngageboostAppWebsites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.IntegerField(blank=True, null=True)),
                ('websiteid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'engageboost_app_websites',
            },
        ),
    ]
