# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-18 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0009_engageboostcmsmenus_engageboostcommissionsettings_engageboostcompanies_engageboostcompaniescrons_eng'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngageboostCrates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crate_barcode', models.CharField(blank=True, max_length=20, null=True)),
                ('shipment_id', models.BigIntegerField(blank=True, null=True)),
                ('order_id', models.BigIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('isdeleted', models.SmallIntegerField(blank=True, null=True)),
                ('isblocked', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'engageboost_crates',
            },
        ),
        migrations.CreateModel(
            name='EngageboostCreditcardSettingInformations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_id', models.IntegerField(blank=True, null=True)),
                ('payment_type_id', models.IntegerField(blank=True, null=True)),
                ('creditcard_id', models.IntegerField(blank=True, null=True)),
                ('isblocked', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='N', max_length=2, null=True)),
                ('isdeleted', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='N', max_length=2, null=True)),
            ],
            options={
                'db_table': 'engageboost_creditcard_setting_informations',
            },
        ),
        migrations.CreateModel(
            name='EngageboostCreditcardTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('value', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.CharField(blank=True, max_length=50, null=True)),
                ('ebay_term', models.CharField(blank=True, max_length=255, null=True)),
                ('isblocked', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2, null=True)),
                ('isdeleted', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2, null=True)),
            ],
            options={
                'db_table': 'engageboost_creditcard_types',
            },
        ),
        migrations.CreateModel(
            name='EngageboostCurrencyMasters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currencyname', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(blank=True, max_length=255, null=True)),
                ('currencysymbol', models.CharField(blank=True, max_length=255, null=True)),
                ('isblocked', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
                ('isdeleted', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
                ('engageboost_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webservices.EngageboostCountries')),
            ],
            options={
                'db_table': 'engageboost_currency_masters',
            },
        ),
        migrations.CreateModel(
            name='EngageboostCurrencyRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engageboost_company_website_id', models.BigIntegerField()),
                ('currency_code', models.CharField(blank=True, max_length=10, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('isbasecurrency', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
                ('isdeleted', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
                ('isblocked', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
                ('createdby', models.IntegerField(default='0')),
                ('updatedby', models.IntegerField(default='0')),
                ('created', models.DateField(blank=True, null=True)),
                ('modified', models.DateField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webservices.EngageboostCountries')),
                ('engageboost_currency_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency_rates', to='webservices.EngageboostCurrencyMasters')),
            ],
            options={
                'db_table': 'engageboost_currency_rates',
            },
        ),
    ]
