# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-18 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0010_engageboostcrates_engageboostcreditcardsettinginformations_engageboostcreditcardtypes_engageboostcur'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngageboostCustomEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('website_id', models.IntegerField(blank=True, null=True)),
                ('page_id', models.IntegerField(blank=True, null=True)),
                ('email_admin', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='y', max_length=2)),
                ('email_user', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
                ('email_from', models.TextField(blank=True, null=True)),
                ('email_bcc', models.TextField(blank=True, null=True)),
                ('admin_subject', models.TextField(blank=True, null=True)),
                ('admin_body', models.TextField(blank=True, null=True)),
                ('user_subject', models.TextField(blank=True, null=True)),
                ('user_body', models.TextField(blank=True, null=True)),
                ('isblocked', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='y', max_length=2)),
                ('isdeleted', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='y', max_length=2)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'engageboost_custom_emails',
            },
        ),
        migrations.CreateModel(
            name='EngageboostCustomFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('website_id', models.IntegerField(blank=True, null=True)),
                ('page_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('ftype', models.CharField(blank=True, max_length=100, null=True)),
                ('def_val', models.CharField(blank=True, max_length=100, null=True)),
                ('required', models.CharField(blank=True, max_length=1, null=True)),
                ('options', models.TextField(blank=True, null=True)),
                ('minlength', models.CharField(blank=True, max_length=20, null=True)),
                ('maxlength', models.CharField(blank=True, max_length=20, null=True)),
                ('rows', models.CharField(blank=True, max_length=5, null=True)),
                ('cols', models.CharField(blank=True, max_length=5, null=True)),
                ('style', models.TextField(blank=True, null=True)),
                ('orders', models.IntegerField(blank=True, null=True)),
                ('isblocked', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='y', max_length=2)),
                ('isdeleted', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='y', max_length=2)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'engageboost_custom_fields',
            },
        ),
        migrations.CreateModel(
            name='EngageboostCustomForms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('website_id', models.IntegerField(blank=True, null=True)),
                ('page_id', models.IntegerField(blank=True, null=True)),
                ('campaign_id', models.IntegerField(blank=True, null=True)),
                ('ip', models.TextField(blank=True, null=True)),
                ('isblocked', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='y', max_length=2)),
                ('isdeleted', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='y', max_length=2)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'engageboost_custom_forms',
            },
        ),
        migrations.CreateModel(
            name='EngageboostCustomValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_form_id', models.IntegerField(blank=True, null=True)),
                ('custom_field_id', models.IntegerField(blank=True, null=True)),
                ('custom_field_value', models.CharField(blank=True, max_length=255, null=True)),
                ('isblocked', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='y', max_length=2)),
                ('isdeleted', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='y', max_length=2)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'engageboost_custom_values',
            },
        ),
    ]
