# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-19 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0012_engageboostcustomeractivities_engageboostcustomerloyaltypoints_engageboostcustomerproductreviews_eng'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngageboostDbWebsitehits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_website_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('visits', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'engageboost_db_websitehits',
            },
        ),
        migrations.CreateModel(
            name='EngageboostDbWebsitestats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_website_id', models.IntegerField(blank=True, null=True)),
                ('revenue', models.IntegerField(blank=True, null=True)),
                ('products', models.IntegerField(blank=True, null=True)),
                ('orders', models.IntegerField(blank=True, null=True)),
                ('customers', models.IntegerField(blank=True, null=True)),
                ('sitevisitors', models.IntegerField(blank=True, null=True)),
                ('uniquevisitors', models.IntegerField(blank=True, null=True)),
                ('amazon', models.IntegerField(blank=True, null=True)),
                ('ebay', models.IntegerField(blank=True, null=True)),
                ('webshop', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'engageboost_db_websitestats',
            },
        ),
        migrations.CreateModel(
            name='EngageboostDbWebsitevisitorshits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_website_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('visits', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'engageboost_db_websitevisitorshits',
            },
        ),
        migrations.CreateModel(
            name='EngageboostDefaultCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_category_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'engageboost_default_categories',
            },
        ),
        migrations.CreateModel(
            name='EngageboostDefaultEmailTypeContents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('email_type', models.CharField(choices=[('H', 'H'), ('T', 'T'), ('HT', 'HT')], default='T', max_length=2)),
                ('email_content', models.TextField(blank=True, null=True)),
                ('email_content_text', models.TextField(blank=True, null=True)),
                ('reply_to_email', models.TextField(blank=True, null=True)),
                ('bcc', models.CharField(blank=True, max_length=255, null=True)),
                ('email_from', models.CharField(blank=True, max_length=255, null=True)),
                ('last_modified', models.DateField(blank=True, null=True)),
                ('isdeleted', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
                ('isblocked', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
                ('order_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'engageboost_default_email_type_contents',
            },
        ),
        migrations.CreateModel(
            name='EngageboostDefaultModuleLayoutFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_layout_section_id', models.BigIntegerField(blank=True, null=True)),
                ('module_list_id', models.IntegerField(blank=True, null=True)),
                ('field_id', models.IntegerField(blank=True, null=True)),
                ('section_col', models.SmallIntegerField(blank=True, null=True)),
                ('section_row', models.SmallIntegerField(blank=True, null=True)),
                ('field_label', models.TextField(blank=True, null=True)),
                ('model_field_value', models.TextField(blank=True, null=True)),
                ('field_type', models.TextField(blank=True, null=True)),
                ('input_type', models.TextField(blank=True, null=True)),
                ('association_value', models.TextField(blank=True, null=True)),
                ('default_values', models.TextField(blank=True, null=True)),
                ('custom_values', models.TextField(blank=True, null=True)),
                ('value_required', models.TextField(choices=[('y', 'y'), ('n', 'n')], default='n', null=True)),
                ('is_system', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2, null=True)),
                ('is_optional', models.SmallIntegerField(blank=True, null=True)),
                ('data_type', models.CharField(blank=True, max_length=100, null=True)),
                ('data_length', models.CharField(blank=True, max_length=100, null=True)),
                ('valid_rule', models.CharField(blank=True, max_length=30, null=True)),
                ('err_msg', models.CharField(blank=True, max_length=200, null=True)),
                ('score', models.CharField(blank=True, max_length=150, null=True)),
                ('ajax_model', models.CharField(blank=True, max_length=255, null=True)),
                ('ajax_field', models.CharField(blank=True, max_length=255, null=True)),
                ('ajax_input_type', models.CharField(blank=True, max_length=255, null=True)),
                ('ajax_update_field_id', models.IntegerField(blank=True, null=True)),
                ('field_msg', models.CharField(blank=True, max_length=255, null=True)),
                ('show_type', models.IntegerField(blank=True, null=True)),
                ('show_market_places', models.CharField(blank=True, max_length=255, null=True)),
                ('show_market_places_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('channel_categories_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'engageboost_default_module_layout_fields',
            },
        ),
        migrations.CreateModel(
            name='EngageboostDefaultModuleLayouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_name', models.CharField(blank=True, max_length=50, null=True)),
                ('module_id', models.IntegerField(blank=True, null=True)),
                ('website_id', models.IntegerField(blank=True, null=True)),
                ('module_name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'engageboost_default_module_layouts',
            },
        ),
        migrations.CreateModel(
            name='EngageboostDefaultModuleLayoutSections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_list_id', models.BigIntegerField(blank=True, null=True)),
                ('module_id', models.IntegerField(blank=True, null=True)),
                ('default_section_id', models.IntegerField(blank=True, null=True)),
                ('section_heading', models.CharField(blank=True, max_length=100, null=True)),
                ('section_order_pos', models.SmallIntegerField(blank=True, null=True)),
                ('seo_activate', models.IntegerField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'engageboost_default_module_layout_sections',
            },
        ),
        migrations.CreateModel(
            name='EngageboostDefaultSections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('module_id', models.IntegerField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('seo_activate', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'engageboost_default_sections',
            },
        ),
        migrations.CreateModel(
            name='EngageboostDefaultsFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=25, null=True)),
                ('field_name', models.CharField(blank=True, max_length=50, null=True)),
                ('associate_value', models.CharField(blank=True, max_length=255, null=True)),
                ('is_optional', models.SmallIntegerField(blank=True, default='0', null=True)),
                ('is_variant', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10, null=True)),
                ('input_type', models.CharField(blank=True, max_length=200, null=True)),
                ('custom_values', models.TextField(blank=True, null=True)),
                ('data_type', models.CharField(blank=True, max_length=100, null=True)),
                ('data_length', models.CharField(blank=True, max_length=100, null=True)),
                ('callback_events', models.TextField(blank=True, null=True)),
                ('err_msg', models.CharField(blank=True, max_length=255, null=True)),
                ('isdeleted', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2, null=True)),
                ('isblocked', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateField(blank=True, null=True)),
                ('modified', models.DateField(blank=True, null=True)),
                ('createdby', models.IntegerField(default='1')),
                ('updatedby', models.IntegerField(default='1')),
            ],
            options={
                'db_table': 'engageboost_defaults_fields',
            },
        ),
        migrations.CreateModel(
            name='EngageboostDeliveryManagers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('zone', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.TextField(blank=True, null=True)),
                ('address1', models.CharField(blank=True, max_length=500, null=True)),
                ('address2', models.CharField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('isdeleted', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2, null=True)),
                ('isblocked', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2, null=True)),
            ],
            options={
                'db_table': 'engageboost_delivery_managers',
            },
        ),
        migrations.CreateModel(
            name='EngageboostDeliveryPlanOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('orders', models.IntegerField(blank=True, null=True)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('time', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shipment_id', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('virtual_vechile_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'engageboost_delivery_plan_order',
            },
        ),
        migrations.CreateModel(
            name='EngageboostDeliverySlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('zone_id', models.IntegerField(blank=True, null=True)),
                ('day_id', models.IntegerField(blank=True, null=True)),
                ('start_time', models.CharField(blank=True, max_length=20, null=True)),
                ('end_time', models.CharField(blank=True, max_length=20, null=True)),
                ('cutoff_start', models.CharField(blank=True, max_length=20, null=True)),
                ('cutoff_end', models.CharField(blank=True, max_length=20, null=True)),
                ('order_qty_per_slot', models.IntegerField(blank=True, null=True)),
                ('isdeleted', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
                ('isblocked', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'engageboost_delivery_slot',
            },
        ),
    ]
