# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-19 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0013_engageboostdbwebsitehits_engageboostdbwebsitestats_engageboostdbwebsitevisitorshits_engageboostdefau'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngageboostDhlZipcodeLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_id', models.IntegerField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('dstarea', models.CharField(blank=True, max_length=255, null=True)),
                ('dstsrvctr', models.CharField(blank=True, max_length=255, null=True)),
                ('dpzone', models.CharField(blank=True, max_length=255, null=True)),
                ('dpflag', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=255, null=True)),
                ('careadesc', models.CharField(blank=True, max_length=255, null=True)),
                ('cscrcddesc', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'engageboost_dhl_zipcode_lists',
            },
        ),
        migrations.CreateModel(
            name='EngageboostDirecpayReturnDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_id', models.IntegerField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=20, null=True)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=4, null=True)),
                ('country', models.CharField(blank=True, max_length=4, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'engageboost_direcpay_return_details',
            },
        ),
        migrations.CreateModel(
            name='EngageboostDiscountMasters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('disc_type', models.IntegerField(blank=True, null=True)),
                ('disc_start_date', models.DateTimeField(blank=True, null=True)),
                ('disc_end_date', models.DateTimeField(blank=True, null=True)),
                ('customer_group', models.CharField(blank=True, max_length=255, null=True)),
                ('discount_type', models.CharField(choices=[('p', 'p'), ('c', 'c')], default='p', max_length=2)),
                ('isdeleted', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
                ('isblocked', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
                ('discount_master_type', models.IntegerField(blank=True, null=True)),
                ('discount_priority', models.IntegerField(blank=True, null=True)),
                ('coupon_code', models.CharField(blank=True, max_length=255, null=True)),
                ('coupon_prefix', models.CharField(blank=True, max_length=50, null=True)),
                ('coupon_suffix', models.CharField(blank=True, max_length=50, null=True)),
                ('coupon_type', models.IntegerField(blank=True, null=True)),
                ('has_multiplecoupons', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
                ('used_coupon', models.IntegerField(blank=True, null=True)),
                ('product_id', models.CharField(blank=True, max_length=255, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('freebies_product_ids', models.CharField(blank=True, max_length=255, null=True)),
                ('freebies_product_sku', models.CharField(blank=True, max_length=500, null=True)),
                ('no_of_quantity_per', models.IntegerField(blank=True, null=True)),
                ('condition_for_freebie_items', models.CharField(blank=True, max_length=100, null=True)),
                ('offer_type', models.CharField(blank=True, max_length=21, null=True)),
                ('up_to_discount', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('updatedby', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'engageboost_discount_masters',
            },
        ),
        migrations.CreateModel(
            name='EngageboostDiscountMastersConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.IntegerField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('all_category_id', models.TextField(blank=True, null=True)),
                ('all_product_id', models.TextField(blank=True, null=True)),
                ('all_customer_id', models.TextField(blank=True, null=True)),
                ('all_day_id', models.CharField(blank=True, max_length=21, null=True)),
                ('condition_type', models.CharField(blank=True, max_length=255, null=True)),
                ('field_type', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateField(blank=True, null=True)),
                ('modified', models.DateField(blank=True, null=True)),
                ('isdeleted', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
                ('isblocked', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
                ('createdby', models.IntegerField(default='0')),
                ('updatedby', models.IntegerField(default='0')),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('discount_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DiscountMastersConditions', to='webservices.EngageboostDiscountMasters')),
            ],
            options={
                'db_table': 'engageboost_discount_masters_conditions',
            },
        ),
        migrations.CreateModel(
            name='EngageboostDiscountMastersCoupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_id', models.IntegerField(blank=True, null=True)),
                ('coupon_code', models.CharField(blank=True, max_length=255, null=True)),
                ('is_used', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
                ('created', models.DateField(blank=True, null=True)),
                ('modified', models.DateField(blank=True, null=True)),
                ('isdeleted', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
                ('isblocked', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
                ('createdby', models.IntegerField(default='0')),
                ('updatedby', models.IntegerField(default='0')),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('discount_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DiscountMastersCoupons', to='webservices.EngageboostDiscountMasters')),
            ],
            options={
                'db_table': 'engageboost_discount_masters_coupons',
            },
        ),
        migrations.CreateModel(
            name='EngageboostDriverLoginDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_id', models.IntegerField(blank=True, null=True)),
                ('vehicle_id', models.IntegerField(blank=True, null=True)),
                ('driver_id', models.IntegerField(blank=True, null=True)),
                ('device_id', models.IntegerField(blank=True, null=True)),
                ('checkin_date', models.DateField(blank=True, null=True)),
                ('checkin_time', models.DateTimeField(blank=True, null=True)),
                ('checkin_kilometer', models.FloatField(blank=True, null=True)),
                ('checkout_time', models.DateTimeField(blank=True, null=True)),
                ('checkout_kilometer', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('isdeleted', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
                ('isblocked', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
            ],
            options={
                'db_table': 'engageboost_driver_login_details',
            },
        ),
        migrations.CreateModel(
            name='EngageboostDriverVeichleMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.IntegerField(blank=True, null=True)),
                ('vehicle_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('shipment_id', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('virtual_vechile_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'engageboost_driver_veichle_map',
            },
        ),
        migrations.CreateModel(
            name='EngageboostEbayBoostCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_category_id', models.BigIntegerField(blank=True, null=True)),
                ('categorylevel', models.IntegerField(blank=True, null=True)),
                ('categoryname', models.CharField(blank=True, max_length=120, null=True)),
                ('categoryparentid', models.IntegerField(blank=True, null=True)),
                ('leafcategory', models.IntegerField(blank=True, null=True)),
                ('autopayenabled', models.IntegerField(blank=True, null=True)),
                ('allowreserveprice', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
                ('minimumreserveprice', models.FloatField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('channel_site_id', models.IntegerField(blank=True, null=True)),
                ('is_variation_enanbled', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2, null=True)),
                ('is_custom_item_itemspecification_enabled', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2, null=True)),
            ],
            options={
                'db_table': 'engageboost_ebay_boost_categories',
            },
        ),
        migrations.CreateModel(
            name='EngageboostEbayItemSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebay_cat_id', models.IntegerField(blank=True, null=True)),
                ('item_specification', models.CharField(blank=True, max_length=255, null=True)),
                ('channel_id', models.IntegerField(blank=True, null=True)),
                ('fieldtype', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'engageboost_ebay_item_specification',
            },
        ),
        migrations.CreateModel(
            name='EngageboostEbayItemSpecificationValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebay_category_id', models.IntegerField(blank=True, null=True)),
                ('item_specification_id', models.IntegerField(blank=True, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('channel_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'engageboost_ebay_item_specification_value',
            },
        ),
        migrations.CreateModel(
            name='EngageboostEbayProductCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebay_condition_id', models.IntegerField(blank=True, null=True)),
                ('ebay_condition_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'engageboost_ebay_product_condition',
            },
        ),
        migrations.CreateModel(
            name='EngageboostEbaystoreCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boost_category_id', models.IntegerField(blank=True, null=True)),
                ('boost_parent_category_id', models.IntegerField(blank=True, null=True)),
                ('ebay_storecategory_id', models.BigIntegerField(blank=True, null=True)),
                ('ebay_storecategory_parent_id', models.BigIntegerField(blank=True, null=True)),
                ('channel_id', models.IntegerField(blank=True, null=True)),
                ('category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category_url', models.CharField(blank=True, max_length=255, null=True)),
                ('isblocked', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2, null=True)),
                ('isdeleted', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'engageboost_ebaystore_categories',
            },
        ),
    ]
