# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-19 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0017_engageboostformuladetails_engageboostfulfillments_engageboostglobalsettingcountries_engageboostgloba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboostgridlayouts',
            name='company_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engageboostgridlayouts',
            name='website_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
