# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-20 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0023_auto_20190220_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngageboostNewsletterSubcribes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('unsubscribe', models.TextField(choices=[('n', 'n'), ('y', 'y')], default='n', max_length=2)),
                ('isdeleted', models.CharField(choices=[('n', 'n'), ('y', 'y')], default='n', max_length=2)),
                ('isblocked', models.CharField(choices=[('n', 'n'), ('y', 'y')], default='n', max_length=2)),
            ],
            options={
                'db_table': 'engageboost_newsletter_subcribes',
            },
        ),
        migrations.CreateModel(
            name='EngageboostOrderStatusSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status_master_id', models.IntegerField(blank=True, null=True)),
                ('website_id', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'engageboost_order_status_settings',
            },
        ),
        migrations.CreateModel(
            name='EngageboostOrderSubscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_id', models.BigIntegerField(blank=True, null=True)),
                ('company_id', models.BigIntegerField(blank=True, null=True)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('isdeleted', models.CharField(choices=[('n', 'n'), ('y', 'y')], default='n', max_length=2)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'engageboost_order_subscribe',
            },
        ),
        migrations.CreateModel(
            name='EngageboostOrderSubscribeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_id', models.BigIntegerField(blank=True, null=True)),
                ('company_id', models.BigIntegerField(blank=True, null=True)),
                ('subscribe_id', models.BigIntegerField(blank=True, null=True)),
                ('order_id', models.BigIntegerField(blank=True, null=True)),
                ('isdeleted', models.CharField(choices=[('n', 'n'), ('y', 'y')], default='n', max_length=2)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'engageboost_order_subscribe_details',
            },
        ),
        migrations.CreateModel(
            name='EngageboostOtherLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'engageboost_other_location',
            },
        ),
        migrations.CreateModel(
            name='EngageboostPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_website_id', models.IntegerField(blank=True, null=True)),
                ('page_name', models.CharField(blank=True, max_length=250, null=True)),
                ('page_title', models.CharField(blank=True, max_length=250, null=True)),
                ('url', models.CharField(blank=True, max_length=250, null=True)),
                ('saved_page', models.CharField(max_length=50)),
                ('meta_key', models.TextField(blank=True, null=True)),
                ('meta_data', models.TextField(blank=True, null=True)),
                ('meta_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('layout', models.IntegerField(blank=True, null=True)),
                ('issaved', models.SmallIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('isblocked', models.SmallIntegerField(blank=True, null=True)),
                ('isdeleted', models.SmallIntegerField(blank=True, null=True)),
                ('ispublished', models.SmallIntegerField(blank=True, null=True)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('device', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'engageboost_pages',
            },
        ),
        migrations.CreateModel(
            name='EngageboostParentCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_category_id', models.IntegerField(blank=True, null=True)),
                ('parent_two_category_id', models.IntegerField(default=0)),
                ('parent_three_category_id', models.IntegerField(default=0)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('isdeleted', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
                ('isblocked', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
            ],
            options={
                'db_table': 'engageboost_parent_categories',
            },
        ),
        migrations.CreateModel(
            name='EngageboostPaymentgatewayMethods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('paymentgateway_type_id', models.IntegerField(blank=True, null=True)),
                ('destination_url', models.TextField(blank=True, null=True)),
                ('destination_sandbox_url', models.TextField(blank=True, null=True)),
                ('notification_url', models.TextField(blank=True, null=True)),
                ('notification_sandbox_url', models.TextField(blank=True, null=True)),
                ('cancel_url', models.TextField(blank=True, null=True)),
                ('cancel_sandbox_url', models.TextField(blank=True, null=True)),
                ('ebay_term', models.CharField(blank=True, max_length=255, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('isblocked', models.CharField(choices=[('n', 'n'), ('y', 'y')], default='n', max_length=2)),
                ('isdeleted', models.CharField(choices=[('n', 'n'), ('y', 'y')], default='n', max_length=2)),
            ],
            options={
                'db_table': 'engageboost_paymentgateway_methods',
            },
        ),
        migrations.CreateModel(
            name='EngageboostPaymentgatewaySettingInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_id', models.IntegerField(blank=True, null=True)),
                ('paymentgateway_method_id', models.IntegerField(blank=True, null=True)),
                ('paymentgateway_type_id', models.IntegerField(blank=True, null=True)),
                ('setting_key', models.TextField(blank=True, null=True)),
                ('setting_val', models.TextField(blank=True, null=True)),
                ('paymentgateway_setting_id', models.IntegerField(blank=True, null=True)),
                ('isblocked', models.CharField(choices=[('n', 'n'), ('y', 'y')], default='n', max_length=2)),
                ('isdeleted', models.CharField(choices=[('n', 'n'), ('y', 'y')], default='n', max_length=2)),
            ],
            options={
                'db_table': 'engageboost_paymentgateway_setting_information',
            },
        ),
        migrations.CreateModel(
            name='EngageboostPaymentgatewaySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentgateway_method_id', models.IntegerField(blank=True, null=True)),
                ('paymentgateway_type_id', models.IntegerField(blank=True, null=True)),
                ('setting_order_by', models.IntegerField(blank=True, null=True)),
                ('setting_label', models.TextField(blank=True, null=True)),
                ('setting_key', models.TextField(blank=True, null=True)),
                ('setting_default_val', models.TextField(blank=True, null=True)),
                ('setting_desc', models.TextField(blank=True, null=True)),
                ('isblocked', models.CharField(choices=[('n', 'n'), ('y', 'y')], default='n', max_length=2)),
                ('isdeleted', models.CharField(choices=[('n', 'n'), ('y', 'y')], default='n', max_length=2)),
            ],
            options={
                'db_table': 'engageboost_paymentgateway_settings',
            },
        ),
        migrations.CreateModel(
            name='EngageboostPaymentgatewaysGlobalsettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_std_url', models.CharField(blank=True, max_length=255, null=True)),
                ('paypal_expresscheckout_url', models.CharField(blank=True, max_length=255, null=True)),
                ('paypal_pro_url', models.CharField(blank=True, max_length=255, null=True)),
                ('ccavenue_url', models.CharField(blank=True, max_length=255, null=True)),
                ('paypal_ipn', models.CharField(blank=True, max_length=255, null=True)),
                ('googlecheckout_url', models.CharField(blank=True, max_length=255, null=True)),
                ('authorize_net_url', models.CharField(blank=True, max_length=255, null=True)),
                ('worldpay_url', models.CharField(blank=True, max_length=255, null=True)),
                ('usaepay_url', models.CharField(blank=True, max_length=255, null=True)),
                ('checkout_url', models.CharField(blank=True, max_length=255, null=True)),
                ('barclaysepdq_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'engageboost_paymentgateways_globalsettings',
            },
        ),
        migrations.CreateModel(
            name='EngageboostPaymentgatewayTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ebay_term', models.TextField(blank=True, null=True)),
                ('order_by', models.IntegerField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('isdeleted', models.CharField(choices=[('n', 'n'), ('y', 'y')], default='n', max_length=2)),
                ('isblocked', models.CharField(choices=[('n', 'n'), ('y', 'y')], default='n', max_length=2)),
            ],
            options={
                'db_table': 'engageboost_paymentgateway_types',
            },
        ),
        migrations.CreateModel(
            name='EngageboostPaymentSetupDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_id', models.IntegerField(blank=True, null=True)),
                ('order_process_paid', models.IntegerField(blank=True, null=True)),
                ('order_process_placed', models.IntegerField(blank=True, null=True)),
                ('email_marketting_type', models.IntegerField(blank=True, null=True)),
                ('contents', models.TextField(blank=True, null=True)),
                ('refund', models.TextField(blank=True, null=True)),
                ('privacy', models.TextField(blank=True, null=True)),
                ('terms_of_service', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'engageboost_payment_setup_details',
            },
        ),
        migrations.CreateModel(
            name='EngageboostTimezones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone_location', models.CharField(blank=True, max_length=255, null=True)),
                ('gmt', models.CharField(blank=True, max_length=255, null=True)),
                ('offset', models.FloatField(blank=True, null=True)),
                ('isblocked', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
                ('isdeleted', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
                ('created', models.DateField(blank=True, null=True)),
                ('modified', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'engageboost_timezones',
            },
        ),
        migrations.CreateModel(
            name='EngageboostWebsitePaymentmethods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engageboost_company_website_id', models.IntegerField(blank=True, null=True)),
                ('engageboost_paymentgateway_method_id', models.IntegerField(blank=True, null=True)),
                ('isblocked', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
                ('isdeleted', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
            ],
            options={
                'db_table': 'engageboost_website_paymentmethods',
            },
        ),
    ]
