# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-26 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0028_engageboostmerchantonereturndetails_engageboostnetazeptreturndetails_engageboostpaypalexpresscheckou'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngageboostPriceFormula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_id', models.IntegerField(blank=True, default='1', null=True)),
                ('formulla_name', models.CharField(blank=True, max_length=255, null=True)),
                ('price_name', models.CharField(blank=True, max_length=255, null=True)),
                ('condition', models.CharField(blank=True, max_length=100, null=True)),
                ('margin', models.IntegerField(blank=True, null=True)),
                ('formulla_type', models.CharField(blank=True, choices=[('customer', 'customer'), ('vendor', 'vendor')], default='customer', max_length=2, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('isblocked', models.CharField(blank=True, choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2, null=True)),
                ('isdeleted', models.CharField(blank=True, choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2, null=True)),
            ],
            options={
                'db_table': 'engageboost_price_formulas',
            },
        ),
    ]
