# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-28 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0029_engageboostpriceformula'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngageboostCreditPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('loyalty_desc', models.TextField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('per_rupees', models.IntegerField(blank=True, null=True)),
                ('min_threshold_points', models.IntegerField(blank=True, null=True)),
                ('loyal_type', models.IntegerField(blank=True, null=True)),
                ('loyal_start_date', models.DateField(blank=True, null=True)),
                ('loyal_end_date', models.DateField(blank=True, null=True)),
                ('customer_group', models.CharField(blank=True, max_length=255, null=True)),
                ('loyalty_expire_limit', models.CharField(blank=True, choices=[('M', 'M'), ('Q', 'Q'), ('HY', 'HY'), ('Y', 'Y')], default='M', max_length=5, null=True)),
                ('status', models.CharField(blank=True, choices=[('y', 'y'), ('n', 'n')], default='y', max_length=255, null=True)),
                ('isblocked', models.CharField(blank=True, choices=[('y', 'y'), ('n', 'n')], default='n', max_length=5, null=True)),
                ('isdeleted', models.CharField(blank=True, choices=[('y', 'y'), ('n', 'n')], default='n', max_length=5, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'engageboost_credit_point',
            },
        ),
        migrations.RenameModel(
            old_name='EngageboostLoyaltyMastersConditions',
            new_name='EngageboostCreditPointConditions',
        ),
        migrations.DeleteModel(
            name='EngageboostLoyaltyMasters',
        ),
        migrations.AlterField(
            model_name='engageboostpriceformula',
            name='formulla_type',
            field=models.CharField(blank=True, choices=[('customer', 'customer'), ('vendor', 'vendor')], default='customer', max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name='engageboostcreditpointconditions',
            table='engageboost_credit_point_conditions',
        ),
    ]
