# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-28 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0030_auto_20190228_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboostcustomers',
            name='auth_user',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='webservices.EngageboostUsers'),
        ),
        migrations.AlterField(
            model_name='engageboostcustomers',
            name='website_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engageboostcustomersaddressbook',
            name='customers_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engageboostcustomersaddressbook',
            name='isblocked',
            field=models.CharField(blank=True, choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='engageboostcustomersaddressbook',
            name='isdeleted',
            field=models.CharField(blank=True, choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2, null=True),
        ),
    ]
