# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-28 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0032_auto_20190228_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboostgridlayouts',
            name='add_edit_url_popup',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engageboostgridlayouts',
            name='folder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='engageboostgridlayouts',
            name='module_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
