# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-19 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0034_engageboostpurchaseorders_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngageboostPurchaseOrderReceivedProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order_id', models.IntegerField(blank=True, null=True)),
                ('purchase_order_product_id', models.IntegerField(blank=True, null=True)),
                ('purchase_order_received_id', models.IntegerField(blank=True, null=True)),
                ('lot_no', models.CharField(blank=True, max_length=20, null=True)),
                ('rack_no', models.CharField(blank=True, max_length=20, null=True)),
                ('received_quantity', models.IntegerField(blank=True, null=True)),
                ('damaged_quantity', models.IntegerField(blank=True, null=True)),
                ('shortage_quantity', models.IntegerField(blank=True, null=True)),
                ('total_quantity', models.IntegerField(blank=True, null=True)),
                ('manufactured_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('expiry_issue_comment', models.TextField(blank=True, null=True)),
                ('expiry_issue', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('goods_condition', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='received', max_length=20)),
                ('created', models.DateField(blank=True, null=True)),
                ('modified', models.DateField(blank=True, null=True)),
                ('isblocked', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
                ('isdeleted', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
            ],
            options={
                'db_table': 'engageboost_purchase_orders_received_product_details',
            },
        ),
        migrations.AlterField(
            model_name='engageboostproductcategories',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_list', to='webservices.EngageboostProducts'),
        ),
    ]
