# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-01 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0034_engageboostpurchaseorders_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngageboostLoyaltyMasters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('applied_in', models.CharField(choices=[('1', 'Fixed'), ('2', 'Percentage')], default='1', max_length=2)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('loyalty_master_type', models.CharField(choices=[('1', 'Earn'), ('2', 'Burn')], default='1', max_length=2)),
                ('isdeleted', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
                ('isblocked', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
                ('amount_spend', models.FloatField(blank=True, null=True)),
                ('loyalty_get', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('updatedby', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'engageboost_loyalty_masters',
            },
        ),
        migrations.CreateModel(
            name='EngageboostLoyaltyMastersConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.IntegerField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('all_category_id', models.TextField(blank=True, null=True)),
                ('all_product_id', models.TextField(blank=True, null=True)),
                ('all_customer_id', models.TextField(blank=True, null=True)),
                ('all_day_id', models.CharField(blank=True, max_length=21, null=True)),
                ('condition_type', models.CharField(blank=True, max_length=255, null=True)),
                ('field_type', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateField(blank=True, null=True)),
                ('modified', models.DateField(blank=True, null=True)),
                ('isdeleted', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
                ('isblocked', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
                ('createdby', models.IntegerField(default='0')),
                ('updatedby', models.IntegerField(default='0')),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('loyalty_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LoyaltyMastersConditions', to='webservices.EngageboostLoyaltyMasters')),
            ],
            options={
                'db_table': 'engageboost_loyalty_masters_conditions',
            },
        ),
        migrations.AlterField(
            model_name='engageboostproductcategories',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_list', to='webservices.EngageboostProducts'),
        ),
    ]
