# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-20 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0035_auto_20190319_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostpurchaseorderreceivedproductdetails',
            name='website_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
