# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-01 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0035_auto_20190401_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engageboostloyaltymastersconditions',
            name='loyalty_master',
        ),
        migrations.DeleteModel(
            name='EngageboostLoyaltyMasters',
        ),
        migrations.DeleteModel(
            name='EngageboostLoyaltyMastersConditions',
        ),
    ]
