# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-26 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0036_engageboostpurchaseorderreceivedproductdetails_website_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboosttempproducts',
            name='customer_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
