# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-01 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0036_auto_20190401_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engageboostcreditpoint',
            old_name='min_threshold_points',
            new_name='loyalty_expire_days',
        ),
        migrations.RemoveField(
            model_name='engageboostcreditpoint',
            name='loyalty_expire_limit',
        ),
        migrations.AddField(
            model_name='engageboostcreditpoint',
            name='applied_as',
            field=models.CharField(choices=[('1', 'Fixed'), ('2', 'Percentage')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='engageboostcreditpointconditions',
            name='all_day_id',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='engageboostcreditpoint',
            name='loyal_type',
            field=models.CharField(choices=[('1', 'Earn'), ('2', 'Burn')], default='1', max_length=2),
        ),
    ]
