# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-26 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0037_auto_20190326_0718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engageboosttempproducts',
            old_name='customer_group',
            new_name='customer_group_id',
        ),
    ]
