# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-01 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0037_auto_20190401_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboostcreditpoint',
            name='applied_as',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], default='fixed', max_length=20),
        ),
        migrations.AlterField(
            model_name='engageboostcreditpoint',
            name='loyal_type',
            field=models.CharField(choices=[('earn', 'Earn'), ('burn', 'Burn')], default='earn', max_length=20),
        ),
    ]
