# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-26 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0038_auto_20190326_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engageboosttempproducts',
            name='po_taxclass',
        ),
        migrations.RemoveField(
            model_name='engageboosttempproducts',
            name='taxclass',
        ),
        migrations.RemoveField(
            model_name='engageboosttempproducts',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='engageboosttempproducts',
            name='po_taxclass_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engageboosttempproducts',
            name='taxclass_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
