# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-01 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0038_auto_20190401_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboostcreditpoint',
            name='applied_as',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], default='fixed', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='engageboostcreditpoint',
            name='loyal_type',
            field=models.CharField(blank=True, choices=[('earn', 'Earn'), ('burn', 'Burn')], default='earn', max_length=20, null=True),
        ),
    ]
