# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-01 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0039_auto_20190401_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboostcreditpoint',
            name='created',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='engageboostcreditpoint',
            name='modified',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
