# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-01 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0040_auto_20190401_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboostcreditpoint',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engageboostcreditpoint',
            name='loyal_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engageboostcreditpoint',
            name='loyal_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engageboostcreditpoint',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
