# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-02 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0041_auto_20190401_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engageboostcreditpointconditions',
            name='loyalty_master_id',
        ),
        migrations.AddField(
            model_name='engageboostcreditpointconditions',
            name='loyalty_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CreditPoint', to='webservices.EngageboostCreditPoint'),
        ),
    ]
