# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-04 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0039_auto_20190326_0743'),
        ('webservices', '0042_auto_20190402_1135'),
    ]

    operations = [
    ]
