# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-04 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0044_auto_20190404_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostcreditpoint',
            name='is_redeem_limited',
            field=models.CharField(blank=True, choices=[('y', 'y'), ('n', 'n')], default='y', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='engageboostcreditpoint',
            name='redeem_amount_type',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], default='fixed', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='engageboostcreditpoint',
            name='redeem_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engageboostcreditpoint',
            name='redeem_type',
            field=models.CharField(blank=True, choices=[('loyalty', 'Loyalty'), ('order', 'Order')], default='loyalty', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='engageboostcreditpoint',
            name='status',
            field=models.CharField(blank=True, choices=[('y', 'y'), ('n', 'n')], default='y', max_length=5, null=True),
        ),
    ]
