# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-05 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0044_auto_20190404_0738'),
        ('webservices', '0045_auto_20190404_0733'),
    ]

    operations = [
    ]
