# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-08 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0046_merge_20190405_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngageboostTempDiscountMasters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('disc_type', models.IntegerField(blank=True, null=True)),
                ('disc_start_date', models.DateTimeField(blank=True, null=True)),
                ('disc_end_date', models.DateTimeField(blank=True, null=True)),
                ('customer_group', models.CharField(blank=True, max_length=255, null=True)),
                ('discount_type', models.CharField(choices=[('p', 'p'), ('c', 'c')], default='p', max_length=2)),
                ('isdeleted', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
                ('isblocked', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
                ('discount_master_type', models.IntegerField(blank=True, choices=[('prodcut Specific', 'Product Specific'), ('coupon specific discount', 'Coupon Specific')], default='prodcut Specific', null=True)),
                ('discount_priority', models.IntegerField(blank=True, null=True)),
                ('coupon_code', models.CharField(blank=True, max_length=255, null=True)),
                ('coupon_prefix', models.CharField(blank=True, max_length=50, null=True)),
                ('coupon_suffix', models.CharField(blank=True, max_length=50, null=True)),
                ('coupon_type', models.IntegerField(blank=True, null=True)),
                ('has_multiplecoupons', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
                ('used_coupon', models.IntegerField(blank=True, null=True)),
                ('product_id', models.CharField(blank=True, max_length=255, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('freebies_product_ids', models.CharField(blank=True, max_length=255, null=True)),
                ('freebies_product_sku', models.CharField(blank=True, max_length=500, null=True)),
                ('no_of_quantity_per', models.IntegerField(blank=True, null=True)),
                ('condition_for_freebie_items', models.CharField(blank=True, max_length=100, null=True)),
                ('offer_type', models.CharField(blank=True, max_length=21, null=True)),
                ('up_to_discount', models.FloatField(blank=True, null=True)),
                ('file_name', models.TextField(blank=True, null=True)),
                ('err_flag', models.IntegerField(blank=True, null=True)),
                ('sku_equals', models.CharField(blank=True, max_length=255, null=True)),
                ('sku_not_equals', models.CharField(blank=True, max_length=255, null=True)),
                ('category_equals', models.CharField(blank=True, max_length=255, null=True)),
                ('category_not_equals', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_equals', models.FloatField(blank=True, null=True)),
                ('amount_equals_greater', models.FloatField(blank=True, null=True)),
                ('amount_equals_less', models.FloatField(blank=True, null=True)),
                ('free_item_sku', models.CharField(blank=True, max_length=255, null=True)),
                ('free_item_quantity', models.CharField(blank=True, max_length=255, null=True)),
                ('weekly_equals', models.CharField(blank=True, max_length=255, null=True)),
                ('weekly_not_equals', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_equals', models.TextField(blank=True, null=True)),
                ('customer_not_equals', models.TextField(blank=True, null=True)),
                ('free_shipping', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_coupon', models.IntegerField(blank=True, null=True)),
                ('error_text', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('updatedby', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'engageboost_temp_discount_masters',
            },
        ),
    ]
