# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-08 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0047_engageboosttempdiscountmasters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboosttempdiscountmasters',
            name='discount_master_type',
            field=models.CharField(blank=True, choices=[('product specific', 'Product Specific'), ('coupon specific discount', 'Coupon Specific')], default='product specific', max_length=255, null=True),
        ),
    ]
