# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-08 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0048_auto_20190408_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboosttempdiscountmasters',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
