# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-10 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0050_auto_20190408_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostdeliveryslot',
            name='based_on',
            field=models.CharField(choices=[('SameDay', 'SameDay'), ('PrevDay', 'PrevDay')], default='SameDay', max_length=20),
        ),
        migrations.AlterField(
            model_name='engageboosttempdiscountmasters',
            name='discount_master_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
