# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-16 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0051_auto_20190410_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostzonemasters',
            name='min_order_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
