# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-24 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0052_engageboostzonemasters_min_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboosttaxrates',
            name='tax_type',
            field=models.CharField(choices=[('VAT', 'VAT'), ('CST', 'CST'), ('Excise Duty', 'Excise Duty')], default='VAT', max_length=20),
        ),
    ]
