# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-02 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0054_engageboostordermaster_pay_txndate'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngageboostMultipleBarcodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=255, null=True)),
                ('default_ean', models.CharField(blank=True, choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('modifiedby', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('isblocked', models.CharField(blank=True, choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2, null=True)),
                ('isdeleted', models.CharField(blank=True, choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barcode_product_id', to='webservices.EngageboostProducts')),
            ],
            options={
                'db_table': 'engageboost_multiple_barcodes',
            },
        ),
        migrations.AddField(
            model_name='engageboosttaxruletables',
            name='isblocked',
            field=models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2),
        ),
        migrations.AddField(
            model_name='engageboosttaxruletables',
            name='isdeleted',
            field=models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2),
        ),
    ]
