# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-02 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0055_engageboostmultiplebarcodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostmultiplebarcodes',
            name='default_ean',
            field=models.CharField(blank=True, choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2, null=True),
        ),
    ]
