# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-03 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0056_engageboostmultiplebarcodes_default_ean'),
        ('webservices', '0055_auto_20190502_1131'),
    ]

    operations = [
    ]
