# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-03 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0057_merge_20190503_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboostcreditpoint',
            name='per_rupees',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engageboostcreditpoint',
            name='points',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engageboostcreditpoint',
            name='redeem_limit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
