# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-08 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0058_auto_20190503_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngageboostOrderPaymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method_id', models.IntegerField(blank=True, null=True)),
                ('payment_type_id', models.IntegerField(blank=True, null=True)),
                ('payment_method_name', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_amount', models.FloatField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('modifiedby', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('isblocked', models.CharField(blank=True, choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2, null=True)),
                ('isdeleted', models.CharField(blank=True, choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2, null=True)),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paymeny_order_details', to='webservices.EngageboostOrdermaster')),
            ],
            options={
                'db_table': 'engageboost_order_payment_details',
            },
        ),
    ]
