# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-09 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0059_engageboostorderpaymentdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngageboostDenominationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_type_id', models.IntegerField(blank=True, null=True)),
                ('payment_method_name', models.CharField(blank=True, max_length=100, null=True)),
                ('currency_amount', models.FloatField(blank=True, null=True)),
                ('currency_count', models.IntegerField(blank=True, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('modifiedby', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('isblocked', models.CharField(blank=True, choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2, null=True)),
                ('isdeleted', models.CharField(blank=True, choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2, null=True)),
                ('order_payment_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paymeny_denomination_details', to='webservices.EngageboostOrderPaymentDetails')),
            ],
            options={
                'db_table': 'engageboost_denomination_details',
            },
        ),
        migrations.AlterField(
            model_name='engageboostordermaster',
            name='received_status',
            field=models.CharField(choices=[('Payment Ok', 'Payment Ok'), ('Excess Of', 'Excess Of'), ('Deficit Of', 'Deficit Of'), ('Hold', 'Hold')], default='Payment Ok', max_length=255),
        ),
    ]
