# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-10 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0059_engageboostorderpaymentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboosttaxsettings',
            name='cst_applicable',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='engageboosttaxsettings',
            name='excise_duty',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
