# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-09 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0060_auto_20190509_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostdenominationdetails',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='engageboostorderpaymentdetails',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
