# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-10 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0062_engageboostdenominationcurrencymaster'),
        ('webservices', '0060_auto_20190510_0622'),
    ]

    operations = [
    ]
