# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-10 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0064_auto_20190510_1043'),
        ('webservices', '0064_engageboostordermaster_pos_device_id'),
    ]

    operations = [
    ]
