# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-10 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0065_merge_20190510_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngageboostTempMultipleBarcodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=255, null=True)),
                ('default_ean', models.CharField(blank=True, choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('err_flag', models.IntegerField(blank=True, max_length=2, null=True)),
                ('error_text', models.CharField(blank=True, max_length=2, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('modifiedby', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('isblocked', models.CharField(blank=True, choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2, null=True)),
                ('isdeleted', models.CharField(blank=True, choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2, null=True)),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_barcode_product_id', to='webservices.EngageboostProducts')),
            ],
            options={
                'db_table': 'engageboost_temp_multiple_barcodes',
            },
        ),
        migrations.RemoveField(
            model_name='engageboostordermaster',
            name='pos_device_id',
        ),
        migrations.RemoveField(
            model_name='engageboostrolemasters',
            name='website_id',
        ),
        migrations.RemoveField(
            model_name='engageboostusers',
            name='access_key',
        ),
        migrations.RemoveField(
            model_name='engageboostusers',
            name='website_id',
        ),
    ]
