# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-10 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0066_auto_20190510_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboosttempmultiplebarcodes',
            name='err_flag',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
