# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-10 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0068_auto_20190510_1300'),
        ('webservices', '0065_merge_20190510_1252'),
    ]

    operations = [
    ]
