# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-10 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0068_auto_20190510_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboosttempmultiplebarcodes',
            name='sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
