# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-10 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0070_engageboostordermaster_pos_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboosttempmultiplebarcodes',
            name='error_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
