# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-13 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0071_auto_20190510_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostmultiplebarcodes',
            name='website_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
