# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-13 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0073_engageboostglobalsettings_applicable_tax'),
        ('webservices', '0069_merge_20190510_1308'),
    ]

    operations = [
    ]
