# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-14 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0074_merge_20190513_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboosttempmultiplebarcodes',
            name='website_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
