# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-15 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0075_engageboosttempmultiplebarcodes_website_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostproductimages',
            name='website_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engageboosttempproductimages',
            name='website_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engageboostpurchaseorderreceivedproducts',
            name='purchase_order_received',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_received_product', to='webservices.EngageboostPurchaseOrdersReceived'),
        ),
    ]
