# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-15 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0076_auto_20190515_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboosttempproductimages',
            name='error_msg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
