# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-15 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0077_engageboosttempproductimages_error_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostvehiclemasters',
            name='vehicle_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
