# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-16 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0078_engageboostvehiclemasters_vehicle_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboosttempproducts',
            name='associated_product_skus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engageboosttempproducts',
            name='cross_product_skus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engageboosttempproducts',
            name='substitude_product_skus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engageboosttempproducts',
            name='upsell_product_skus',
            field=models.TextField(blank=True, null=True),
        ),
    ]
