# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-16 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0079_auto_20190516_0916'),
        ('webservices', '0079_auto_20190515_1235'),
    ]

    operations = [
    ]
