# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-16 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0081_auto_20190516_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboostshipmentorderproducts',
            name='shipment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
