# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-17 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0082_auto_20190516_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engageboosttrentspicklistproducts',
            name='trent_picklist_id',
        ),
        migrations.AddField(
            model_name='engageboosttrentspicklistproducts',
            name='trent_picklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trents_picklist_products', to='webservices.EngageboostTrentPicklists'),
        ),
    ]
