# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-17 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0083_auto_20190517_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboosttrentpicklists',
            name='zone_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
