# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-20 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0084_engageboosttrentpicklists_zone_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostshipmentorderproducts',
            name='trent_picklist_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engageboostshipmentorders',
            name='trent_picklist_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
