# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-20 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0085_auto_20190520_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboostshipmentorders',
            name='shipment_status',
            field=models.CharField(blank=True, choices=[('Created', 'Created'), ('Packed', 'Packed'), ('Picking', 'Picking'), ('Invoicing', 'Invoicing'), ('Create Shipment', 'Create Shipment'), ('Shipment Processing', 'Shipment Processing'), ('Ready to Ship', 'Ready to Ship'), ('Ready to Dispatch', 'Ready to Dispatch'), ('Dispatched', 'Dispatched'), ('Shipped', 'Shipped'), ('Completed', 'Completed')], default='Created', max_length=100, null=True),
        ),
    ]
