# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-22 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0087_auto_20190520_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engageboostcrates',
            name='shipment_id',
        ),
        migrations.AddField(
            model_name='engageboostcrates',
            name='trent_picklist_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
