# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-22 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0088_auto_20190522_0644'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngageboostPriceTypeMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateField(blank=True, null=True)),
                ('modified', models.DateField(blank=True, null=True)),
                ('isdeleted', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
                ('isblocked', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
            ],
            options={
                'db_table': 'engageboost_price_type_master',
            },
        ),
        migrations.AddField(
            model_name='engageboostchannelcurrencyproductprice',
            name='warehouse_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engageboostchannelcurrencyproductprice',
            name='website_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engageboostchannelcurrencyproductprice',
            name='price_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webservices.EngageboostPriceTypeMaster'),
        ),
    ]
