# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-23 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0091_engageboostproductpricetypemaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engageboostchannelcurrencyproductprice',
            name='price_type',
        ),
        migrations.AddField(
            model_name='engageboostchannelcurrencyproductprice',
            name='product_price_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webservices.EngageboostProductPriceTypeMaster'),
        ),
        migrations.AlterField(
            model_name='engageboostpricetypemaster',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engageboostpricetypemaster',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engageboostproductpricetypemaster',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engageboostproductpricetypemaster',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
