# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-23 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0092_auto_20190523_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboostproducts',
            name='default_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
