# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-24 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0093_auto_20190523_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engageboostchannelcurrencyproductprice',
            old_name='quantity',
            new_name='max_quantity',
        ),
        migrations.AddField(
            model_name='engageboostchannelcurrencyproductprice',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engageboostchannelcurrencyproductprice',
            name='min_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engageboostchannelcurrencyproductprice',
            name='product_price_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_price_type_master', to='webservices.EngageboostProductPriceTypeMaster'),
        ),
    ]
