# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-24 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0094_auto_20190524_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostproductpricetypemaster',
            name='max_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engageboostproductpricetypemaster',
            name='min_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
