# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-28 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0095_auto_20190524_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostshipments',
            name='website_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engageboostshippingmasters',
            name='website_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engageboosttaxsettings',
            name='apply_customer_tax',
            field=models.CharField(choices=[('Before Discount', 'Before Discount'), ('After Discount', 'After Discount')], default='Before Discount', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engageboosttaxsettings',
            name='apply_discount_on_prices',
            field=models.CharField(choices=[('Excluding Tax', 'Excluding Tax'), ('Including Tax', 'Including Tax'), ('Including and Excluding Tax', 'Including and Excluding Tax')], default='null', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engageboosttaxsettings',
            name='catalog_prices',
            field=models.CharField(choices=[('Including Tax', 'Including Tax'), ('Excluding Tax', 'Excluding Tax')], default='Excluding Tax', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engageboosttaxsettings',
            name='cst_applicable',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='null', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engageboosttaxsettings',
            name='display_full_tax_summary',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='null', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engageboosttaxsettings',
            name='display_prices',
            field=models.CharField(choices=[('Excluding Tax', 'Excluding Tax'), ('Including Tax', 'Including Tax'), ('Including and Excluding Tax', 'Including and Excluding Tax')], default='null', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engageboosttaxsettings',
            name='display_product_prices_in_catalog',
            field=models.CharField(choices=[('Excluding Tax', 'Excluding Tax'), ('Including Tax', 'Including Tax'), ('Including and Excluding Tax', 'Including and Excluding Tax')], default='null', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engageboosttaxsettings',
            name='display_shipping_amount',
            field=models.CharField(choices=[('Excluding Tax', 'Excluding Tax'), ('Including Tax', 'Including Tax'), ('Including and Excluding Tax', 'Including and Excluding Tax')], default='null', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engageboosttaxsettings',
            name='display_shipping_prices',
            field=models.CharField(choices=[('Excluding Tax', 'Excluding Tax'), ('Including Tax', 'Including Tax'), ('Including and Excluding Tax', 'Including and Excluding Tax')], default='null', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engageboosttaxsettings',
            name='display_subtotal',
            field=models.CharField(choices=[('Excluding Tax', 'Excluding Tax'), ('Including Tax', 'Including Tax'), ('Including and Excluding Tax', 'Including and Excluding Tax')], default='null', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engageboosttaxsettings',
            name='display_zero_tax_subtotal',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='null', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engageboosttaxsettings',
            name='include_tax_in_grand_total',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='null', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engageboosttaxsettings',
            name='isblocked',
            field=models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='engageboosttaxsettings',
            name='isdeleted',
            field=models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='engageboosttaxsettings',
            name='shipping_price',
            field=models.CharField(choices=[('Excluding Tax', 'Excluding Tax'), ('Including Tax', 'Including Tax')], default='Excluding Tax', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engageboosttaxsettings',
            name='tax_calculation_based_on',
            field=models.CharField(choices=[('Shipping Address', 'Shipping Address'), ('Billing Address', 'Billing Address')], default='Shipping Address', max_length=50, null=True),
        ),
    ]
