# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-29 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0096_auto_20190528_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostordermaster',
            name='grn_created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
