# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-30 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0097_engageboostordermaster_grn_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='assign_wh',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='cess',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='cess_percentage',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='cgst',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='cgst_percentage',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='deleted_quantity',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='grn_quantity',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='igst',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='igst_percentage',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='product_discount_price',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='product_discount_price_base',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='product_discount_rate',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='product_excise_duty',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='product_price',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='product_price_base',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='product_tax_price',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='quantity',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='returns',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='sgst',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='sgst_percentage',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='shipping_cgst',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='shipping_cgst_percentage',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='shipping_igst',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='shipping_igst_percentage',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='shipping_sgst',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='shipping_sgst_percentage',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='shortage',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='status',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='tax_percentage',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='trents_picklist_id',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
