# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-31 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0098_auto_20190530_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngageboostAdditionalGlobalsettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings_key', models.TextField(blank=True, null=True)),
                ('settings_value', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('isblocked', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2, null=True)),
                ('isdeleted', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2, null=True)),
            ],
            options={
                'db_table': 'engageboost_additional_global_settings',
            },
        ),
    ]
