# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-30 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0098_auto_20190530_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='giftwrap_price',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='giftwrap_price_base',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='giftwrap_tax',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='giftwrap_tax_base',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='shipping_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='shipping_discount_base',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='shipping_price',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='shipping_price_base',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='shipping_tax',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='shipping_tax_base',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10, null=True),
        ),
    ]
