# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-03 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0099_engageboostadditionalglobalsettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engageboostdeliveryslot',
            old_name='cutoff_end',
            new_name='cutoff_time',
        ),
        migrations.RemoveField(
            model_name='engageboostdeliveryslot',
            name='cutoff_start',
        ),
    ]
