# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-03 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0100_auto_20190603_1015'),
        ('webservices', '0099_auto_20190530_0738'),
    ]

    operations = [
    ]
