# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-04 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0103_auto_20190604_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostinvoicemaster',
            name='trent_picklist_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
