# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-04 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0104_engageboostinvoicemaster_trent_picklist_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engageboostwarehousesuppliermappings',
            name='base_cost',
        ),
    ]
