# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-07 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0107_auto_20190606_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngageboostNotifyOrderArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('driver_id', models.IntegerField(blank=True, null=True)),
                ('lat_val', models.CharField(blank=True, max_length=100, null=True)),
                ('long_val', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'engageboost_notify_order_area',
            },
        ),
    ]
