# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-11 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0108_engageboostnotifyorderarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboostpages',
            name='isblocked',
            field=models.CharField(choices=[('n', 'n'), ('y', 'y')], default='n', max_length=2),
        ),
        migrations.AlterField(
            model_name='engageboostpages',
            name='isdeleted',
            field=models.CharField(choices=[('n', 'n'), ('y', 'y')], default='n', max_length=2),
        ),
        migrations.AlterField(
            model_name='engageboostpages',
            name='ispublished',
            field=models.CharField(choices=[('n', 'n'), ('y', 'y')], default='n', max_length=2),
        ),
        migrations.AlterField(
            model_name='engageboostpages',
            name='issaved',
            field=models.CharField(choices=[('n', 'n'), ('y', 'y')], default='n', max_length=2),
        ),
    ]
