# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-12 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0110_engageboostcategorymasterslang_engageboostlanguagemasters'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EngageboostLanguageMasters',
        ),
        migrations.AddField(
            model_name='engageboostlanguages',
            name='lang_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
