# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-13 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0111_auto_20190612_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engageboostcmsmenus',
            old_name='image',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='engageboostcmsmenus',
            name='category',
        ),
        migrations.RemoveField(
            model_name='engageboostcmsmenus',
            name='product',
        ),
        migrations.AddField(
            model_name='engageboostcmsmenus',
            name='category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engageboostcmsmenus',
            name='flag',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='engageboostcmsmenus',
            name='product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engageboostcmsmenus',
            name='isblocked',
            field=models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2),
        ),
        migrations.AlterField(
            model_name='engageboostcmsmenus',
            name='isdeleted',
            field=models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2),
        ),
        migrations.AlterField(
            model_name='engageboostcmsmenus',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
    ]
