# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-13 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0112_auto_20190613_0524'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngageboostCmsPageSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_website_id', models.IntegerField()),
                ('temp_id', models.IntegerField()),
                ('page_id', models.IntegerField()),
                ('widgets', models.IntegerField(blank=True, null=True)),
                ('property_value', models.TextField(blank=True, null=True)),
                ('created', models.DateField(blank=True, null=True)),
                ('modified', models.DateField(blank=True, null=True)),
                ('createdby', models.IntegerField(null=True)),
                ('updatedby', models.IntegerField(null=True)),
                ('lang', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'engageboost_cms_page_settings',
            },
        ),
        migrations.CreateModel(
            name='EngageboostEmktFunnelPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funnel_id', models.IntegerField(blank=True, null=True)),
                ('landing_page_id', models.IntegerField(blank=True, null=True)),
                ('landing_page_temp_id', models.IntegerField(blank=True, null=True)),
                ('thankyou_page_id', models.IntegerField(blank=True, null=True)),
                ('thankyou_page_temp_id', models.IntegerField(blank=True, null=True)),
                ('company_website_id', models.IntegerField(blank=True, null=True)),
                ('email_campaign_id', models.IntegerField(blank=True, null=True)),
                ('campaign_type', models.CharField(blank=True, max_length=255, null=True)),
                ('product_ids', models.CharField(blank=True, max_length=255, null=True)),
                ('createdby', models.IntegerField(null=True)),
                ('updatedby', models.IntegerField(null=True)),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('isblocked', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
                ('isdeleted', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
            ],
            options={
                'db_table': 'engageboost_emkt_funnel_page',
            },
        ),
    ]
