# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-18 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0113_engageboostcmspagesettings_engageboostemktfunnelpages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engageboostinvoicemaster',
            name='sap_invoice_date',
        ),
        migrations.RemoveField(
            model_name='engageboostinvoicemaster',
            name='sap_invoice_no',
        ),
        migrations.RemoveField(
            model_name='engageboostinvoicemaster',
            name='sap_sales_order_no',
        ),
    ]
