# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-19 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0114_auto_20190618_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboostordermaster',
            name='shipment_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='engageboostordermaster',
            name='trent_picklist_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
