# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-19 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0115_engageboostbrandmasterslang'),
        ('webservices', '0115_auto_20190619_0727'),
    ]

    operations = [
    ]
