# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-20 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0118_engageboostshipments_zone_id'),
        ('webservices', '0118_engageboostproductmasterslang'),
    ]

    operations = [
    ]
