# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-20 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0119_merge_20190620_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboostbrandmasterslang',
            name='field_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engageboostcategorymasterslang',
            name='field_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engageboostproductmasterslang',
            name='field_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
