# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-20 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0120_auto_20190620_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostdiscountmasters',
            name='warehouse_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
