# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-24 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0060_engageboostwarehousemanager_role'),
        ('webservices', '0121_engageboostdiscountmasters_warehouse_id'),
    ]

    operations = [
    ]
