# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-24 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0121_engageboostcustomfieldmasterslang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboostdriverlogindetails',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
