# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-24 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0122_merge_20190624_0820'),
        ('webservices', '0122_merge_20190624_0809'),
    ]

    operations = [
    ]
