# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-24 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0123_merge_20190624_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engageboostwarehousemanager',
            name='role',
        ),
        migrations.AddField(
            model_name='engageboostpages',
            name='template_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
