# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-25 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0124_merge_20190625_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostcustomfieldmasterslang',
            name='category_id',
            field=models.IntegerField(blank=True, null=True),
        )#,
        # migrations.AddField(
        #     model_name='engageboostpages',
        #     name='template_image',
        #     field=models.TextField(blank=True, null=True),
        # ),
    ]
