# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-25 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0124_auto_20190624_0925'),
        ('webservices', '0122_auto_20190624_1212'),
    ]

    operations = [
    ]
