# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-25 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0125_merge_20190625_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostpages',
            name='template_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
