# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-27 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0127_auto_20190626_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostwarehousemasters',
            name='max_distance_sales',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
