# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-04 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0128_engageboostwarehousemasters_max_distance_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngageboostCategoryWarehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('isblocked', models.CharField(blank=True, choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2, null=True)),
                ('isdeleted', models.CharField(blank=True, choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2, null=True)),
                ('Warehouse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webservices.EngageboostWarehouseMasters')),
                ('category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webservices.EngageboostCategoryMasters')),
            ],
            options={
                'db_table': 'engageboost_category_warehouse',
            },
        ),
    ]
