# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-04 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0129_engageboostcategorywarehouse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engageboostcategorywarehouse',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='engageboostcategorywarehouse',
            old_name='Warehouse_id',
            new_name='warehouse',
        ),
    ]
