# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-04 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0131_engageboostproductcustomfieldmasterslang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboostdiscountmasters',
            name='warehouse_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
