# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-05 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0132_auto_20190704_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboostcategorymasters',
            name='show_navigation',
            field=models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N')], default='N', max_length=2, null=True),
        ),
    ]
