# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-08 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0132_auto_20190704_1023'),
        ('webservices', '0125_auto_20190625_1320'),
    ]

    operations = [
    ]
