# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-11 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0133_auto_20190705_0518'),
        ('webservices', '0133_merge_20190708_1617'),
    ]

    operations = [
    ]
