# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-11 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0134_merge_20190711_0549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engageboostcategorymasters',
            name='show_navigation',
        ),
    ]
