# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-17 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0136_engageboostcategorymasters_show_navigation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboostcrates',
            name='isblocked',
            field=models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2),
        ),
        migrations.AlterField(
            model_name='engageboostcrates',
            name='isdeleted',
            field=models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2),
        ),
    ]
