# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-15 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0124_auto_20190624_0959'),
        ('webservices', '0136_engageboostcategorymasters_show_navigation'),
    ]

    operations = [
    ]
