# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-17 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0137_auto_20190717_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostshipmentorders',
            name='isblocked',
            field=models.CharField(blank=True, choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='engageboostshipmentorders',
            name='isdeleted',
            field=models.CharField(blank=True, choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2, null=True),
        ),
    ]
