# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-15 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0137_merge_20190715_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostwarehousemanager',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
