# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-15 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0139_engageboostwarehousemanager_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engageboostwarehousemanager',
            name='role',
        ),
    ]
