# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-25 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0140_auto_20190725_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboosttrafficreports',
            name='totalvisit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engageboosttrafficreportsbrowsers',
            name='totalvisit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engageboosttrafficreportsmobiles',
            name='totalvisit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
