# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-15 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0141_engageboostwarehousemanager_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engageboostcategorymasters',
            name='show_navigation',
        ),
    ]
