# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-29 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0141_auto_20190725_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostdefaultsfields',
            name='visible_in_filter',
            field=models.IntegerField(default=0),
        ),
    ]
