# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-30 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0142_engageboostdefaultsfields_visible_in_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostorderproducts',
            name='cost_price',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='engageboostorderproducts',
            name='mrp',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
    ]
