# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-30 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0143_auto_20190730_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostchannelcurrencyproductprice',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engageboostchannelcurrencyproductprice',
            name='mrp',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='engageboostchannelcurrencyproductprice',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
