# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-31 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0144_auto_20190730_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngageboostOrderPriceChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_id', models.IntegerField(blank=True, default=0, null=True)),
                ('warehouse_id', models.IntegerField(blank=True, default=0, null=True)),
                ('order_id', models.BigIntegerField(blank=True, default=0, null=True)),
                ('product_id', models.IntegerField(blank=True, default=0, null=True)),
                ('old_product_price', models.FloatField(blank=True, default='0', null=True)),
                ('new_product_price', models.FloatField(blank=True, default='0', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created', models.DateField(blank=True, null=True)),
                ('modified', models.DateField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, default='0', null=True)),
            ],
            options={
                'db_table': 'engageboost_order_price_changes',
            },
        ),
    ]
