# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-31 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0145_engageboostorderpricechange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboostorderpricechange',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engageboostorderpricechange',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
