# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-02 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0147_auto_20190802_1223'),
        ('webservices', '0147_engageboostorderproducts_substitute_product_id'),
    ]

    operations = [
    ]
