# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-02 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0148_merge_20190802_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engageboostproductpricetypemaster',
            name='warehouse_id',
        ),
    ]
