# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-05 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0151_engageboosttempproductprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboosttempproductprice',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engageboosttempproductprice',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
