# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-05 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0152_auto_20190805_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboosttempproductprice',
            name='price_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engageboosttempproductprice',
            name='sku',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engageboosttempproductprice',
            name='warehouse_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
