# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-06 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0154_auto_20190806_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engageboostcategorybanners',
            name='banner_description',
        ),
        migrations.AddField(
            model_name='engageboostcategorybannersimages',
            name='banner_caption1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engageboostcategorybannersimages',
            name='banner_caption2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
