# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-06 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0155_auto_20190806_0637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engageboostcategorybannersimages',
            old_name='end_time',
            new_name='end_date',
        ),
    ]
