# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-06 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0156_auto_20190806_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboostcategorybannersimages',
            name='category_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
