# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-06 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0143_engageboostcategorymasters_show_navigation'),
        ('webservices', '0157_auto_20190806_0705'),
    ]

    operations = [
    ]
