# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-07 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0160_engageboostproductpricetypemaster_warehouse_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostcategorybanners',
            name='banner_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='engageboostcategorybanners',
            name='banner_link_to',
            field=models.CharField(choices=[('external link', 'external link'), ('promotion', 'promotion'), ('category', 'category')], default='category', max_length=20),
        ),
        migrations.AddField(
            model_name='engageboostcategorybanners',
            name='end_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engageboostcategorybanners',
            name='is_notification_enabled_val',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='engageboostcategorybanners',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='engageboostcategorybanners',
            name='notification_msg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engageboostcategorybanners',
            name='primary_image_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='engageboostcategorybanners',
            name='promotion_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engageboostcategorybanners',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
