# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-12 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0162_auto_20190812_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engageboostcategorybannersimages',
            name='category_banner',
        ),
        migrations.RemoveField(
            model_name='engageboostcategorybanners',
            name='banner_description',
        ),
        migrations.RemoveField(
            model_name='engageboostcategorybanners',
            name='banner_link_to',
        ),
        migrations.RemoveField(
            model_name='engageboostcategorybanners',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='engageboostcategorybanners',
            name='is_notification_enabled_val',
        ),
        migrations.RemoveField(
            model_name='engageboostcategorybanners',
            name='link',
        ),
        migrations.RemoveField(
            model_name='engageboostcategorybanners',
            name='notification_msg',
        ),
        migrations.RemoveField(
            model_name='engageboostcategorybanners',
            name='primary_image_name',
        ),
        migrations.RemoveField(
            model_name='engageboostcategorybanners',
            name='promotion_id',
        ),
        migrations.RemoveField(
            model_name='engageboostcategorybanners',
            name='start_date',
        ),
        migrations.DeleteModel(
            name='EngageboostCategoryBannersImages',
        ),
    ]
