# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-12 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0164_engageboostcategorybannersimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engageboostcategorybannersimages',
            name='category_banner',
        ),
        migrations.DeleteModel(
            name='EngageboostCategoryBannersImages',
        ),
    ]
