# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-13 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0166_engageboostcategorybannersimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engageboostcategorybanners',
            name='applicable_for',
        ),
        migrations.RemoveField(
            model_name='engageboostcategorybannersimages',
            name='mobile_image_name',
        ),
        migrations.AddField(
            model_name='engageboostcategorybannersimages',
            name='applicable_for',
            field=models.CharField(choices=[('mobile', 'mobile'), ('web', 'web'), ('category', 'category')], default='category', max_length=20),
        ),
    ]
