# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-23 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0167_auto_20190813_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngageboostAdvancedSearchLayouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.IntegerField(blank=True, null=True)),
                ('columns', models.TextField(blank=True, null=True)),
                ('field', models.TextField(blank=True, null=True)),
                ('field_type', models.CharField(blank=True, choices=[('string', 'string'), ('int', 'int')], default='int', max_length=20, null=True)),
                ('input_type', models.CharField(blank=True, choices=[('string', 'string'), ('int', 'int')], default='text', max_length=20, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('search_module', models.CharField(blank=True, max_length=100, null=True)),
                ('title_field_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('isblocked', models.CharField(blank=True, choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2, null=True)),
                ('isdeleted', models.CharField(blank=True, choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2, null=True)),
                ('createdby', models.IntegerField(blank=True, default='0', null=True)),
                ('updatedby', models.IntegerField(blank=True, default='0', null=True)),
            ],
            options={
                'db_table': 'engageboost_advanced_search_layouts',
            },
        ),
        migrations.CreateModel(
            name='EngageboostAdvancedSearchModules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_id', models.IntegerField(blank=True, null=True)),
                ('module', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('search_type', models.CharField(blank=True, choices=[('e', 'Elastic'), ('d', 'Database')], default='d', max_length=2, null=True)),
                ('isblocked', models.CharField(blank=True, choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2, null=True)),
                ('isdeleted', models.CharField(blank=True, choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2, null=True)),
                ('createdby', models.IntegerField(blank=True, default='0', null=True)),
                ('updatedby', models.IntegerField(blank=True, default='0', null=True)),
            ],
            options={
                'db_table': 'engageboost_advanced_search_modules',
            },
        ),
        migrations.AlterField(
            model_name='engageboostcategorybannersimages',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engageboostcategorybannersimages',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engageboostproductstocks',
            name='real_stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='engageboostproductstocks',
            name='safety_stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='engageboostproductstocks',
            name='stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='engageboostproductstocks',
            name='virtual_stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
