# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-27 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0168_auto_20190823_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostbrandmasters',
            name='brand_logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
