# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-27 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0169_engageboostbrandmasters_brand_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboosttempproductimages',
            name='product',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
