# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-27 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0170_auto_20190827_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engageboosttempproductprice',
            name='product_price_type',
        ),
        migrations.DeleteModel(
            name='EngageboostTempProductPrice',
        ),
    ]
