# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-23 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0174_auto_20190911_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostbrandmasters',
            name='category_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='engageboostbrandmasters',
            name='slug',
            field=models.TextField(blank=True, null=True),
        ),
    ]
