# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-23 07:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0175_auto_20190923_0716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engageboostbrandmasters',
            old_name='category_url',
            new_name='brand_url',
        ),
    ]
