# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-23 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0176_auto_20190923_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboostbrandmasters',
            name='website_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
