# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-23 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0177_auto_20190923_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostdeliveryslot',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webservices.EngageboostWarehouseMasters'),
        ),
    ]
