# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-24 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0178_engageboostdeliveryslot_warehouse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engageboosttempproducts',
            old_name='ean',
            new_name='barcodes',
        ),
    ]
