# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-24 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0179_auto_20190924_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboosttempproducts',
            name='ean',
            field=models.TextField(blank=True, null=True),
        ),
    ]
