# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-30 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0180_engageboosttempproducts_ean'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngageboostBrandWarehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('isblocked', models.CharField(blank=True, choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2, null=True)),
                ('isdeleted', models.CharField(blank=True, choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webservices.EngageboostBrandMasters')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webservices.EngageboostWarehouseMasters')),
            ],
            options={
                'db_table': 'engageboost_brand_warehouse',
            },
        ),
        migrations.AddField(
            model_name='engageboostadvancedsearchlayouts',
            name='value_field_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='engageboostadvancedsearchmodules',
            name='screen_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='engageboostcategorybanners',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webservices.EngageboostWarehouseMasters'),
        ),
        migrations.AddField(
            model_name='engageboostcustomersaddressbook',
            name='area_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engageboostorderactivity',
            name='product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engageboostorderactivity',
            name='purchase_order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engageboostwarehousesuppliermappings',
            name='base_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engageboostwarehousesuppliermappings',
            name='sale_per_pack_unit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engageboostwarehousesuppliermappings',
            name='supplier_sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='engageboosttempproductcustomfields',
            name='field_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
