# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-30 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0181_auto_20190930_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboosttemporaryshoppingcarts',
            name='warehouse_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
