# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-01 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0182_engageboosttemporaryshoppingcarts_warehouse_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostwarehousemasters',
            name='warehouse_logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
