# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-01 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0183_auto_20191001_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboostrolemasters',
            name='isblocked',
            field=models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2),
        ),
        migrations.AlterField(
            model_name='engageboostrolemasters',
            name='isdeleted',
            field=models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2),
        ),
    ]
