# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-02 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0184_auto_20191001_1423'),
        ('webservices', '0183_engageboostwarehousemasters_warehouse_logo'),
    ]

    operations = [
    ]
