# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-21 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0185_merge_20191002_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostvehiclemasters',
            name='warehouse_ids',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
