# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-21 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0186_engageboostvehiclemasters_warehouse_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostdeliverymanagers',
            name='warehouse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
