# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-21 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0187_engageboostdeliverymanagers_warehouse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engageboostdeliverymanagers',
            old_name='warehouse',
            new_name='warehouse_ids',
        ),
    ]
