# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-22 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0188_auto_20191021_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostorderproducts',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10, null=True),
        ),
    ]
