# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-22 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0189_engageboostorderproducts_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engageboostchannelcurrencyproductprice',
            name='product_id',
        ),
        migrations.AddField(
            model_name='engageboostchannelcurrencyproductprice',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webservices.EngageboostProducts'),
        ),
    ]
