# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-22 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0190_auto_20191022_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboostchannelcurrencyproductprice',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_price', to='webservices.EngageboostProducts'),
        ),
    ]
