# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-23 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0192_auto_20191023_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostemailtypecontents',
            name='warehouse_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
