# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-04 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0193_engageboostemailtypecontents_warehouse_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostcustomerloyaltypoints',
            name='remaining_balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engageboostcustomerloyaltypoints',
            name='view_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
