# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-06 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0194_auto_20191104_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboostshipmentorderproducts',
            name='grn_quantity',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='engageboostshipmentorderproducts',
            name='returns',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='engageboostshipmentorderproducts',
            name='shortage',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
