# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-06 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0194_auto_20191104_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngageboostMastercardPgReturnDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_id', models.IntegerField(blank=True, null=True)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('tracking_id', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_ref_no', models.CharField(blank=True, max_length=50, null=True)),
                ('order_status', models.CharField(blank=True, max_length=20, null=True)),
                ('failure_message', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=100, null=True)),
                ('card_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status_code', models.CharField(blank=True, max_length=100, null=True)),
                ('status_message', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(blank=True, max_length=5, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('billing_name', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_address', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_city', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_state', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_zip', models.IntegerField(blank=True, null=True)),
                ('billing_country', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_tel', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_email', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_name', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_address', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_city', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_state', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_zip', models.IntegerField(blank=True, null=True)),
                ('delivery_country', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_tel', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'engageboost_mastercard_payment_gateway_return_details',
            },
        ),
    ]
