# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-06 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0195_auto_20191106_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostshipmentorders',
            name='return_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engageboostshipmentorders',
            name='return_driver_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
