# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-06 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0196_auto_20191106_0835'),
        ('webservices', '0195_engageboostmastercardpgreturndetails'),
    ]

    operations = [
    ]
