# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-27 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0197_merge_20191106_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboostimportedtempproductstocks',
            name='is_imported',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
