# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-01-10 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0198_auto_20191127_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostccavenueupgradedreturndetails',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engageboostccavenueupgradedreturndetails',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
