# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-01-28 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0199_auto_20200110_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngageboostAppVersionControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_a', models.CharField(blank=True, max_length=50, null=True)),
                ('version_i', models.CharField(blank=True, max_length=50, null=True)),
                ('is_mandatory', models.CharField(blank=True, choices=[('y', 'y'), ('n', 'n')], default='y', max_length=5, null=True)),
                ('upgrade_to', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'enageboost_app_version_control',
            },
        ),
    ]
