# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-12 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0200_engageboostappversioncontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboostorderproducts',
            name='weight',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
    ]
