# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-16 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0201_auto_20200212_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboostwarehousemasters',
            name='max_distance_sales',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
    ]
