# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-19 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0203_engageboostvisitcontacts_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostvisitcontacts',
            name='user_id',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
