# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-19 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0204_engageboostvisitcontacts_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboostvisitcontacts',
            name='telph',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
