# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-26 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0206_auto_20200324_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostgroups',
            name='warehouse_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engageboostrolemasters',
            name='warehouse_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engageboostusers',
            name='warehouse_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
