# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-27 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0207_auto_20200326_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboostgroups',
            name='warehouse_id',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='engageboostrolemasters',
            name='warehouse_id',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='engageboostusers',
            name='warehouse_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
