# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-18 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0209_auto_20200515_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostwarehousemasters',
            name='min_order_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='engageboostinvoicemaster',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_order', to='webservices.EngageboostOrdermaster'),
        ),
    ]
