# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-06 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0210_auto_20200618_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngageboostAllUserDeviceToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, default='0', null=True)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('device_token', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('os_version', models.CharField(blank=True, max_length=100, null=True)),
                ('device_type', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'enageboost_alluser_devicetoken',
            },
        ),
    ]
