# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-30 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0213_engageboostccavenueupgradedreturndetails_si_ref_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostccavenueupgradedreturndetails',
            name='payment_response_full',
            field=models.TextField(blank=True, null=True),
        ),
    ]
