# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-21 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0216_auto_20200925_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostcategorywarehouse',
            name='product_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
