# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-22 06:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0217_engageboostcategorywarehouse_product_count'),
        ('webservices', '0217_auto_20201022_0542'),
    ]

    operations = [
    ]
