# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-09 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0218_merge_20201022_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboosttemplateindustrymasters',
            name='store_type_categories_selected',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
