# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-05 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0219_engageboosttemplateindustrymasters_store_type_categories_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostappversioncontrol',
            name='appstore_check',
            field=models.CharField(blank=True, choices=[('y', 'y'), ('n', 'n')], default='y', max_length=5, null=True),
        ),
    ]
