# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-18 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0220_engageboostappversioncontrol_appstore_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostorderproducts',
            name='custom_field_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='engageboostorderproducts',
            name='custom_field_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='engageboosttemporaryshoppingcarts',
            name='custom_field_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='engageboosttemporaryshoppingcarts',
            name='custom_field_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
