# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-03-02 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0221_auto_20210118_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagebooststates',
            name='state_name_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
