# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-03-02 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0222_engagebooststates_state_name_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostcustomersaddressbook',
            name='is_selected',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
