# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-04-14 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0223_engageboostcustomersaddressbook_is_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostordermaster',
            name='billing_landmark',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='engageboostordermaster',
            name='delivery_landmark',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
