# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-04-14 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0224_auto_20210414_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engageboostdiscountmasters',
            name='warehouse_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
