# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-04-14 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0225_auto_20210414_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='engageboostdiscountmasters',
            name='usage_limit_per_user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
