# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-04-30 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0226_engageboostdiscountmasters_usage_limit_per_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngageboostUserSIList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('si_ref_no', models.CharField(blank=True, max_length=50, null=True)),
                ('is_default', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='y', max_length=2)),
                ('isdeleted', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
                ('isblocked', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=2)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webservices.EngageboostCustomers')),
            ],
            options={
                'db_table': 'engageboost_usersi_list',
            },
        ),
    ]
