# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-05-03 14:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0227_engageboostusersilist'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngageboostProcessQueueMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_type', models.CharField(choices=[('price', 'price'), ('inventory', 'inventory'), ('image', 'image'), ('product', 'product'), ('discount', 'discount')], default='n', max_length=15)),
                ('weight', models.IntegerField(default=0)),
                ('pending_count', models.IntegerField(default=0)),
                ('is_running', models.CharField(choices=[('y', 'y'), ('n', 'n')], default='n', max_length=15)),
                ('modified_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
            options={
                'db_table': 'engageboost_process_queue_master',
            },
        ),
        migrations.CreateModel(
            name='EngageboostUpdateQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_state', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed')], default='Pending', max_length=15)),
                ('process_type', models.CharField(choices=[('single', 'single'), ('bulk', 'bulk')], default='bulk', max_length=15)),
                ('operation_for', models.CharField(choices=[('price', 'price'), ('inventory', 'inventory'), ('image', 'image'), ('product', 'product'), ('discount', 'discount')], default='price', max_length=15)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('process_queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webservices.EngageboostProcessQueueMaster')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webservices.EngageboostProducts')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webservices.EngageboostWarehouseMasters')),
            ],
            options={
                'db_table': 'engageboost_update_queue',
            },
        ),
    ]
