# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-05-21 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0228_engageboostprocessqueuemaster_engageboostupdatequeue'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='engageboostupdatequeue',
        #     name='discount',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webservices.EngageboostDiscountMasters'),
        # ),
        migrations.AddField(
            model_name='engageboostupdatequeue',
            name='prev_products',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engageboostupdatequeue',
            name='prev_warehouses',
            field=models.TextField(blank=True, null=True),
        ),
    ]
