//
//  AlertClass.swift
//  GoGrocery
//
//  Created by NAV63 on 27/05/20.
//  Copyright © 2020 BMS-09-M. All rights reserved.
//

import Foundation
/*
let Email = "Please enter email"
let Password = "Please enter password"
let isValidEmail = "Please enter email"
let Product_Details = "Product Details";
let Home = "Home";
let "Search" = "Search";
let "Offer" = "Offer";
let "Profile" = "Profile";
let "All My Orders" = "My Orders";
let Delivery_Address" = "Delivery Address";
let Notification" = "Notification";
let "Currencey" = "Currencey";
let "Change Language" = "Change Language";
let "Loyality Points" = "Loyality Points";
let "Invite Friends" = "Invite Friends";
let "Customer Support" = "Customer Support";
let "Rate Our App" = "Rate Our App";
let "Logout" = "Logout";
let "BasraCenter" = "Basra Center";
let "LogoutMessage" = "Do you want to logout..";
let "Yes" = "YES";
let "No" = "NO";
let "OK" = "OK";
let "Message" = "Message";
let "My Cart" = "My Cart";
let "My WishList" = "My WishList";
let "My Account" = "My Account";
let "Login" = "Login";
let "deals_of_the_day" = "Deals of the day";
let "best_sell_product" = "Best sell product";
let "viewAll" = "View all";
let "Filter" = "Filter  ";
let "Sort" = "Sort  ";
let "Sort_By" = "SORT BY";
let "Price_Low_to_High" = "Price - Low to High";
let "Price_high_to_Low" = "Price - high to Low";
let "Newest_First" = "Newest First";
let "categories" = "CATEGORIES";
let "PRICE" = "PRICE";
let "clear" = "CLEAR";
let "Apply" = "APPLY";
let "Product_Details" = "Product Details";
let "About" = "About";
let "Benefits" = "Benefits";
let "Other_Info" = "Other Info";
let "No_Info_Added_Yet" = "No Info Added Yet";
let "Review & Rating" = "Review & Rating";
let "Average_Rating" = "Average Rating";
let "5_star" = "5 star";
let "4_star" = "4 star";
let "3_star" = "3 star";
let "2_star" = "2 star";
let "1_star" = "1 star";
let "See_all_Reviews" = "See all Reviews";
let "Rate_&_Write_Reviews" = "Rate & Write Reviews";
let "ADD_TO_CART" = "  ADD TO CART";
let "GO_TO_CART" = "  GO TO CART";
let "SAVE_FOR_LATER" = "  SAVE FOR LATER";
let "SAVED_FOR_LATER" = "  SAVED FOR LATER";
let "Available_quantities_for" = "Available quantities for";
let "Successfully_added_to_cart" = "Successfully added to cart";
let "Successfully_added_to_wishlist" = "Successfully added to wishlist";
let "Successfully_removed_from_wishlist" = "Successfully removed from wishlist";
let "Success" = "Success";
let "Popular_Products" = "Popular Products";
let "Similar_Products" = "Similar Products";
let "Order_Summary" = "Order Summary";
let "Subtotal" = "Subtotal";
let "Coupon_Discount" = "Coupon Discount";
let "Includes_Product_Discount" = "Includes Product Discount";
let "Handling_Charges" = "Handling Charges";
let "Shipping_Charges" = "Shipping Charges";
let "Estimated_tax" = "Estimated tax";
let "Total_Amount" = "Total Amount";
let "CHECKOUT" = "CHECKOUT";
let "My_Cart" = "My Cart";
let "CONTINUE" = "CONTINUE";
let "Total_saved" = "Total saved";
let "Remove_Item" = "Remove Item";
let "remove_message" = "Are you sure you want to remove this item?";
let "Remove" = "Remove";
let" Cancel" = "Cancel";
let "Your_cart_is_empty" = "Your cart is empty!";
let "Add_items_to_it_now" = "Add items to it now.";
let "Shop_now" = "Shop now";
let "Default" = "Default";
let "CHANGE_ADDRESS" = "CHANGE ADDRESS";
let "Change_Address_s" = "Change Address";
let "Delivery_Options" = "Delivery Options";
let "Select_Slot_Timing" = "Select Slot Timing";
let "Apply_Promo_Code" = "Apply Promo Code";
let "PLACE_ORDER" = "PLACE ORDER";
let "Select_Delivery_Slot" = "Select Delivery Slot";
let "You_have_saved" = "You have saved";
let "Invalid_Coupon_Code" = "Invalid Coupon Code";
let "Please_select_delivery_slot" = "Please select delivery slot";
let "Delivery" = "Delivery";
let "Payment" = "Payment";
let "Total" = "Total";
let "Select_Payment_Option" = "Select Payment Option";
let" Delivery_to" = "Delivery to";
let "PAY_NOW" = "PAY NOW";
let "Payments" = "Payments";
let "success_payment_message" = "Order successfully placed. \n Thank you for your order! \n \n We are processing your order and you will recieve an email with order details. \n Once the order has been shipped you will recieve another email with the";
let "Order_Tracking" = "Order Tracking";
let "link" = "link";
let "Your_order_ID" = "Your order ID";
let "Payment_Sucessfull" = "Payment Sucessfull";
let "CONTINUE_SHOPPING" = "CONTINUE SHOPPING";
let "Select_Address" = "Select Address";
let "Add_New_Address" = "Add New Address";
let "Edit" = "Edit";
let "Delete" = "Delete";
let "DELIVER_HERE" = "DELIVER HERE";
let "Successfully_deleted" = "Successfully deleted";
let "Success" = "Success";
let "First_Name" = "First Name";
let "Last_Name" = "Last Name";
let "Contact_Number" = "Contact Number ";
let "Alternate_Contact_Number" = "Alternate Contact Number";
let "Personal_Details" = "Personal Details";
let "Address_Details" = "Address Details";
let "Address" = "Address *";
let "City" = "City *";
let "Region" = "Region *";
let "set_default_address" = "Set this as my default delivery address";
let "ADD_ADDRESS" = "Add Address";
let "Address_by_GPS" = "Address by GPS";
let "Address_created_successfully" = "Address created successfully";
let "Address_updated_successfully" = "Address updated successfully";
let "Update_Address" = "Update Address";
let "First_Name_is_required" = "First Name is required.";
let "Last_Name_is_required" = "Last Name is required.";
let "Contact_number_is_required" = "Contact number is required.";
let Alternate_Contact_number_is_required" = "Alternate Contact number is required.";
let "Contact_number_should_be_atleast_8_digit" = "Contact number should be atleast 8 digit.";
let "Alternate_Contact_number_should_be_atleast_8_digit" = "Alternate Contact number should be atleast 8 digit.";
let "address_is_required." = "address is required.";
let "city_is_required" = "city is required.";
let "province_is_required" = "province is required.";
let "Error" = "Error";
let "Select_City" = "Select City";
let "Select_Region" = "Select Region";
let "Email_address" = "Email address";
let "Select_Gender" = "Select Gender";
let "Male" = "Male";
let "Female" = "Female";
let "Change_Password" = "Change Password";
let "Deactivate_Account" = "Deactivate Account";
let "UPDATE" = "UPDATE";
let "Edit_Profile" = "Edit Profile";
let "Profile_updated_successfully" = "Profile updated successfully";
let "SIGN_IN" = "SIGN IN";
let "Password" = "Password";
let "Sign_In" = "Sign In";
let "OR" = "OR";
let "Forgot_Password" = "Forgot Password?";
let "New_Here_Sign_Up " = "New Here? Sign Up ";
let "Create_Your_Account" = "Create Your Account";
let "CREATE_ACCOUNT" = "CREATE ACCOUNT";
let "Already_have_an_account_Login" = "Already have an account? Login";
let "Confirm_Password" = "Confirm Password";
let "Email_is_required" = "Email is required";
let "Password_is_required" = "Password is required";
let "Email_address_is_not_valid" = "Email address is not valid.";
let "Mobile_number_is_required" = "Mobile number is required.";
let "Mobile_number_is_not_valid" = "Mobile number is not valid.";
let "Password_length_message" = "Password length should be atleast 8 characters";
let "Password_not_matched" = "Password and confirm password doesnt match.";
let "Search_for_products_and_brands" = "Search for products and brands";
let "Recent_Search" = "Recent Search";
let "You_May_Be_Interested_In" = "You May Be Interested In";
let "My_Wishlist" = "My Wishlist";
let "Order_No" = "Order No";
let "My_Orders" = "My Orders";
let "Items" = "Items";
let "Order_Status" = "Order Status : ";
let "Standard_Delivery" = "Standard Delivery";
let Out_of_stock = "Out of stock";
let error_msg_enter_first_name = "First Name should not be empty"
let error_msg_enter_name = "Name should not be empty"
let error_msg_enter_carrier_code = "Carrier Code(CC) should not be empty"
let error_msg_enter_last_name = "Last Name should not be empty"
let error_msg_enter_email = "Email Address should not be empty"
let error_msg_enter_valid_email = "Enter valid email Address"
let error_msg_enter_7_digit_mobile_no = "Mobile number should be 7 digit"
//  <string name="error_msg_enter_mobile_no">Mobile Number should not be empty
//  <string name="error_msg_enter_password">Password should not be empty
//  <string name="error_msg_enter_password_lenght">Password at least 6 Character
//  <string name="error_msg_enter_password_policy">Password must contain at least one upper and lower case letter, number and special character
//  <string name="error_msg_enter_confirm_password">Please enter confirm password</string>
//  <string name="error_msg_enter_confirm_password_match">Confirm Password doesn\'t match</string>
//  <string name="error_msg_enter_registered_email">Please enter registered email</string>
//  <string name="error_msg_enter_registered_email_forgot">Registered Email address should not be empty</string>
//  <string name="error_msg_enter_old_password">Please enter old password</string>
//  <string name="error_msg_enter_new_password">Please enter new password</string>
//  <string name="error_msg_enter_mobile">Enter Mobile Number</string>
//  <string name="error_msg_select_gender">Select Gender</string>
//  <string name="error_msg_enter_address">Enter Address</string>
//  <string name="error_msg_enter_city">Enter City</string>
//  <string name="error_msg_enter_region">Enter Region</string>
//  <string name="error_msg_enter_review_title_is_empty">Review title is empty</string>
//  <string name="error_msg_enter_review_description_is_empty">Review description is empty</string>
//  <string name="error_msg_enter_rating_can_not_be_zero">Rating cannot be zero!!</string>
//  <string name="error_msg_login_cancelled">Login Cancelled!</string>
//  <string name="error_msg_please_select_any_one_address">Please Select Any One Address!</string>
//  <string name="error_msg_please_choose_delivery_slot">Please choose a delivery slot</string>
//  <string name="error_msg_please_add_delivery_address">Please Add delivery Address</string>
//  <string name="error_msg_no_delivery_slot_available">No delivery slots available</string>
//  <string name="error_msg_enter_your_query">Enter your Query</string>
//  <string name="error_msg_cvv_less_than_three_digit">CVV should be less than three digit</string>
//  <string name="error_msg_space_not_allowed">Space not allowed</string>
//  <string name="error_msg_your_savelist_is_empty">Your Savelist is empty!</string>


*/

