FROM nginx:latest
VOLUME /var/log/nginx/log
## Copy our default nginx config
COPY conf.d/nginx.conf /etc/nginx/nginx.conf
## Remove default nginx website
RUN rm -rf /usr/share/nginx/html/*
CMD ["nginx", "-g", "daemon off;"]






